import { User, Project, Report, DashboardSummary, DashboardCharts } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u-sarah-manager',
    email: 'manager@company.com',
    fullName: 'Sarah Kim',
    role: 'MANAGER',
    department: 'Engineering Leadership',
    title: 'Engineering Manager',
    avatarColor: '#ec3013',
    active: true,
    reportCount: 0,
  },
  {
    id: 'u-alex-member',
    email: 'alex@company.com',
    fullName: 'Alex Chen',
    role: 'TEAM_MEMBER',
    department: 'Frontend Engineering',
    title: 'Senior Frontend Engineer',
    avatarColor: '#2563eb',
    active: true,
    reportCount: 4,
  },
  {
    id: 'u-dana-member',
    email: 'dana@company.com',
    fullName: 'Dana Lee',
    role: 'TEAM_MEMBER',
    department: 'Platform Engineering',
    title: 'DevOps / Cloud Engineer',
    avatarColor: '#059669',
    active: true,
    reportCount: 3,
  },
  {
    id: 'u-marcus-member',
    email: 'marcus@company.com',
    fullName: 'Marcus Vance',
    role: 'TEAM_MEMBER',
    department: 'Backend Systems',
    title: 'Backend Systems Engineer',
    avatarColor: '#7c3aed',
    active: true,
    reportCount: 3,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-mobile',
    name: 'Mobile App Redesign',
    code: 'MAR-01',
    description: 'Cross-platform mobile client with offline-first local queue and biometric auth',
    status: 'ACTIVE',
    reportCount: 4,
  },
  {
    id: 'proj-cloud',
    name: 'Cloud Migration',
    code: 'CLM-02',
    description: 'Multi-region AWS EKS Kubernetes migration and container optimization',
    status: 'ACTIVE',
    reportCount: 3,
  },
  {
    id: 'proj-tooling',
    name: 'Internal Tooling',
    code: 'INT-03',
    description: 'Developer infrastructure, telemetry, and automated weekly report engines',
    status: 'ACTIVE',
    reportCount: 3,
  },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  totalMembers: 3,
  totalSubmitted: 2,
  pendingReviews: 1,
  needsCorrectionCount: 1,
  approvedCount: 2,
  complianceRate: 67,
  openBlockers: 4,
};

export const MOCK_DASHBOARD_CHARTS: DashboardCharts = {
  velocityTrend: [
    { weekDate: '2026-08-18', weekLabel: 'W34', plannedTasks: 8, completedTasks: 8 },
    { weekDate: '2026-08-25', weekLabel: 'W35', plannedTasks: 9, completedTasks: 8 },
    { weekDate: '2026-09-01', weekLabel: 'W36', plannedTasks: 7, completedTasks: 5 },
    { weekDate: '2026-09-08', weekLabel: 'W37', plannedTasks: 8, completedTasks: 6 },
  ],
  statusByMember: [
    {
      id: 'u-alex-member',
      name: 'Alex Chen',
      email: 'alex@company.com',
      avatarColor: '#2563eb',
      reportCount: 4,
      completionRate: 90,
      approved: 2,
      submitted: 1,
      needsCorrection: 0,
      draft: 1,
      approvedPct: 50,
      submittedPct: 25,
      needsCorrectionPct: 0,
      draftPct: 25,
    },
    {
      id: 'u-dana-member',
      name: 'Dana Lee',
      email: 'dana@company.com',
      avatarColor: '#059669',
      reportCount: 3,
      completionRate: 75,
      approved: 1,
      submitted: 0,
      needsCorrection: 1,
      draft: 1,
      approvedPct: 33,
      submittedPct: 0,
      needsCorrectionPct: 33,
      draftPct: 33,
    },
    {
      id: 'u-marcus-member',
      name: 'Marcus Vance',
      email: 'marcus@company.com',
      avatarColor: '#7c3aed',
      reportCount: 3,
      completionRate: 85,
      approved: 2,
      submitted: 1,
      needsCorrection: 0,
      draft: 0,
      approvedPct: 67,
      submittedPct: 33,
      needsCorrectionPct: 0,
      draftPct: 0,
    },
  ],
  projectWorkload: [
    { id: 'proj-mobile', name: 'Mobile App Redesign', code: 'MAR-01', hours: 82, reportCount: 4 },
    { id: 'proj-cloud', name: 'Cloud Migration', code: 'CLM-02', hours: 64, reportCount: 3 },
    { id: 'proj-tooling', name: 'Internal Tooling', code: 'INT-03', hours: 58, reportCount: 3 },
  ],
  timeBreakdown: [
    { name: 'Development', hours: 112, percentage: 55, color: '#ec3013' },
    { name: 'Testing', hours: 38, percentage: 19, color: '#2563eb' },
    { name: 'Meetings', hours: 28, percentage: 14, color: '#d97706' },
    { name: 'Documentation', hours: 26, percentage: 12, color: '#059669' },
  ],
};
